"""Sizheng models exported under admin model names — drop-in replacement for `from models import ...`."""
from models_sizheng import (
    SizhengBranch as Branch,
    SizhengPartyGroup as PartyGroup,
    SizhengMember as Member,
    SizhengLearningMaterial as LearningMaterial,
    SizhengLearningRecord as LearningRecord,
    SizhengLearningTask as LearningTask,
    SizhengTaskMaterial as TaskMaterial,
    SizhengTaskAssignment as TaskAssignment,
    SizhengQuestion as Question,
    SizhengAnswerRecord as AnswerRecord,
    SizhengExam as Exam,
    SizhengExamQuestion as ExamQuestion,
    SizhengExamAssignment as ExamAssignment,
    SizhengWritingTemplate as WritingTemplate,
    SizhengWritingRecord as WritingRecord,
    SizhengQuizProgress as QuizProgress,
    SizhengPointRecord as PointRecord,
    SizhengTopic as Topic,
    SizhengTopicItem as TopicItem,
    SizhengLearningNote as LearningNote,
    SizhengChatHistory as ChatHistory,
    SizhengMeeting as Meeting,
    SizhengNotice as Notice,
    SizhengTodo as Todo,
    SizhengDocument as Document,
    SizhengSchedule as Schedule,
    SizhengDevelopmentRecord as DevelopmentRecord,
    SizhengMemberContact as MemberContact,
    SizhengDues as Dues,
    SizhengAssistance as Assistance,
    SizhengVolunteer as Volunteer,
    SizhengAdminUser as AdminUser,
    SizhengOperationLog as OperationLog,
    SizhengSystemConfig as SystemConfig,
    SizhengDataDict as DataDict,
    SizhengDisciplineStudy as DisciplineStudy,
    SizhengWarningEdu as WarningEdu,
    SizhengPartyTransfer as PartyTransfer,
    SizhengFloatingMember as FloatingMember,
    SizhengRegulation as Regulation,
    SizhengArchive as Archive,
    SizhengDuesReceipt as DuesReceipt,
    SizhengDuesPublic as DuesPublic,
    SizhengAssessmentIndicator as AssessmentIndicator,
    SizhengPeerEvaluation as PeerEvaluation,
    SizhengInspection as Inspection,
    SizhengSpecialBrand as SpecialBrand,
    SizhengBranchShowcase as BranchShowcase,
    SizhengSpecialActivity as SpecialActivity,
)

# MEETING_TYPES is the same list — re-export from models
from models import MEETING_TYPES
